Add an interactive state machine for the negotiation process
BBMRI-ERIC/negotiator-v3 pull request #41
Opened 2023-04-27 06:22 UTC by RadovanTomik

2023-05-16 12:20 UTC, svituz requested changes

2023-05-16 12:38 UTC, RadovanTomik commented on src/main/java/eu/bbmri/eric/csit/service/negotiator/api/dto/negotiation/NegotiationDTO.java
> +  private String status;
It does not make sense to store enum value as JSON, resourcesStatus is a JSON containing res_id as key and status as value. How would you propose to rewrite it?

2023-05-18 07:32 UTC, RadovanTomik commented on src/main/java/eu/bbmri/eric/csit/service/negotiator/service/NegotiationStateServiceImpl.java
> +    public Set<NegotiationEvent> getPossibleEvents(String negotiationId, String resourceId) {
The method checks for the stateMachine with a corresponding Id. That state machine gets created everytime the create() merhod in negotiationService is called. Should it also check for the entities in their repositories?

2023-05-18 08:41 UTC, svituz approved these changes

2023-05-18 12:13 UTC, merged